### ISSUE TITLE
Mudar de Lolipop a Hostgator.

### ISSUE THREAD

**Issue by Epotignano** [CeiboIT/sof-tokyo-node-server#1]
https://user.lolipop.jp/ en este link esta el login.
permisos:
sheacom. lolipop.jp
password: sofaries2015
De ahi descargar los archivos, por FTP, con base de dato y todo incluido (Podés preguntarle a jose como se hace, que ya lo ha hecho)
Despues nos tenemos que mover a hostgator.com y acá ir a
https://portal.hostgator.com/login
los permisos son
user: tdnb1207@gmail.com
pass: Sofemiliano2016 en la pestaña de hosting, tenemos que seleccionar sof.tokyo dentro de la categoria Shared package, al otro ignorarlo.
Y ahí toca figurarse como Mudar el sitio con todas sus caracteristicas a hostgator.

**Comment by matiascaputti** [comment]
done.

**Comment by Epotignano** [comment]
Faltan los DNS no sean malas!

Potignano Emiliano - CeiboIT

web: www.ceiboit.com
Linkedin: https://ar.linkedin.com/pub/emiliano-potignano/76/242/192
Github: https://github.com/Epotignano
phone: +54 221 525 5778
address: 11 num 2175 b/510 & 511, La Plata, Buenos Aires, Argentina.

2016-01-05 11:21 GMT-03:00 Matías Caputti notifications@github.com:
