### ISSUE TITLE
JSON Auth API

### ISSUE THREAD

**Issue by Epotignano** [CeiboIT/sof-tokyo-node-server#13]

**Comment by matiascaputti** [comment]
Instalación de plugin JSON API AUTH.
Documentación: https://es.wordpress.org/plugins/json-api-auth/
Requiere tener previamente instalado JSON API. Una vez que están ambas carpetas en /wp-content/plugins se deben activar desde el menú de administración de WordPress, en la solapa Plugins.

![captura de pantalla 2016-01-05 a las 11 42 22 a m](https://cloud.githubusercontent.com/assets/7065401/12117741/6ae76188-b3a1-11e5-8c46-7f4d011be8d0.png)

Luego activar los controladores en Ajustes > JSON API
![captura de pantalla 2016-01-05 a las 11 54 39 a m](https://cloud.githubusercontent.com/assets/7065401/12118058/2fc3dbca-b3a3-11e5-9aa1-c3b5121d47c8.png)

**Comment by matiascaputti** [comment]
Instalación de plugin JSON API USER.
Documentación: https://es.wordpress.org/plugins/json-api-user/
Configuración igual a JSON API AUTH.
![captura de pantalla 2016-01-05 a las 12 01 27 p m](https://cloud.githubusercontent.com/assets/7065401/12118238/16cd2c74-b3a4-11e5-9450-df4c37e989a5.png)

**Comment by Epotignano** [comment]
Ya podemos logear un user a traves de la API???

Potignano Emiliano - CeiboIT

web: www.ceiboit.com
Linkedin: https://ar.linkedin.com/pub/emiliano-potignano/76/242/192
Github: https://github.com/Epotignano
phone: +54 221 525 5778
address: 11 num 2175 b/510 & 511, La Plata, Buenos Aires, Argentina.

2016-01-05 12:00 GMT-03:00 Matías Caputti notifications@github.com:

**Comment by matiascaputti** [comment]
Flujo para Login de usuario:

```
Se llama a /api/auth/login/{username}/{password} 
y devuelve una Session Cookie, que se guarda 
mientras el usuario esté logueado. 
Para cerrar sesión se elimina esa Session Cookie 
del localStorage. 
Para chequear si la Session Cookie es 
válida se llama a /api/auth/is_authorized/{cookie}.
```

Flujo para Registro de usuario:

```
Se llama a /api/auth/nonce/{controller}/{method} para obtener 
un Nonce (en este caso controller: user y method: register), y se llama luego a 
/api/auth/register/{username}/{email}/{nonce}/{display_name} 
que creará al usuario, sin contraseña aún. 
Para generar una contraseña y enviarla al email del 
usuario se llama a /api/auth/reset_password/{username} 
(este método sirve tanto para crear la primera 
contraseña como para resetear la contraseña de cualquier usuario).
```

Los demás métodos del módulo de AUTH se pueden ver en /api
