### ISSUE TITLE
Products list debe ser el equivalente a la pagina de inicio

### ISSUE THREAD

**Issue by Epotignano** [CeiboIT/sof-tokyo-node-server#15]
Esto se consigue con sof.tokyo/?json=1

**Comment by matiascaputti** [comment]
Sisi, productsList funciona de esa misma forma, pero trae de a 4 por página como me habías pedido, pero si querés saco eso límite para que traiga todos.

**Comment by Epotignano** [comment]
Nono, que traiga de a pocos, lo vamos probadno, porque a veces rompe la
app, pongo ese limite para que no tengamos ese problema, el limite de 4 no
lo cambies.

Potignano Emiliano - CeiboIT

web: www.ceiboit.com
Linkedin: https://ar.linkedin.com/pub/emiliano-potignano/76/242/192
Github: https://github.com/Epotignano
phone: +54 221 525 5778
address: 11 num 2175 b/510 & 511, La Plata, Buenos Aires, Argentina.
