### ISSUE TITLE
Permitir agregar url de fotos en los posts.

### ISSUE THREAD

**Issue by Epotignano** [CeiboIT/sof-tokyo-node-server#35]
En vez de enviar un archivo, enviaremos un archivo con una foto cargada a través de cloudinary

**Comment by matiascaputti** [comment]
/api/metadata/images/product

 {
     productId: 15,
     field: 'sofbackend__sof_work_meta__postImage',
     value: 'http:cloudinary.com/klgjdsñkl32'
}
