### ISSUE TITLE
Mapear todos los campos para el registro de usuario igual que en Sof.tokyo web

### ISSUE THREAD

**Issue by Epotignano** [CeiboIT/sof-tokyo-node-server#40]

**Comment by matiascaputti** [comment]
done.

**Comment by Epotignano** [comment]
Grosoooooo

Potignano Emiliano - CeiboIT

web: www.ceiboit.com
Linkedin: https://ar.linkedin.com/pub/emiliano-potignano/76/242/192
Github: https://github.com/Epotignano
phone: +54 221 525 5778
address: 11 num 2175 b/510 & 511, La Plata, Buenos Aires, Argentina.

2016-01-29 10:36 GMT-03:00 Matías Caputti notifications@github.com:
