### ISSUE TITLE
Permitir al usuario crear una lista con sus post preferidos.

### ISSUE THREAD

**Issue by Epotignano** [CeiboIT/sof-tokyo-node-server#52]
El usuario debe poder guardar referencias a id de posts que le hayan interesado, de esta forma podrá tener sus posts favoritos siempre a mano! :D

**Comment by sebastiancesar** [comment]
Desde que vista el usuario puede tildar un post de favorito?
Esa funcionalidad ya está implementada en el backend de wp? o en el backend de node?

**Comment by sebastiancesar** [comment]
La funcionalidad no está presente en el wp, así que hay que implementarla en el backend.
Pero estaría disponible solo para la versión mobile

**Comment by Epotignano** [comment]
si, ya esta hablado de que esto solo va a implentarse en la versión mobile.

Potignano Emiliano - CeiboIT

web: www.ceiboit.com
Linkedin: https://ar.linkedin.com/pub/emiliano-potignano/76/242/192
Github: https://github.com/Epotignano
phone: +54 221 525 5778
address: 11 num 2175 b/510 & 511, La Plata, Buenos Aires, Argentina.

**Comment by Epotignano** [comment]
Buscaron algun plugin de wp para saber que no puede implementarase ahi?

Potignano Emiliano - CeiboIT

web: www.ceiboit.com
Linkedin: https://ar.linkedin.com/pub/emiliano-potignano/76/242/192
Github: https://github.com/Epotignano
phone: +54 221 525 5778
address: 11 num 2175 b/510 & 511, La Plata, Buenos Aires, Argentina.

**Comment by sebastiancesar** [comment]
Por el momento, agrego un botón en la vista de detalle de un post, que sea el que dispara el POST hacia el bacckend de node en "api/favorites" con { id: '21312312' }

**Comment by Epotignano** [comment]
en que qued+o entonces? que grande seba frontendeando en React!

Potignano Emiliano - CeiboIT

web: www.ceiboit.com
Linkedin: https://ar.linkedin.com/pub/emiliano-potignano/76/242/192
Github: https://github.com/Epotignano
phone: +54 221 525 5778
address: 11 num 2175 b/510 & 511, La Plata, Buenos Aires, Argentina.

**Comment by matiascaputti** [comment]
Los plugins de WP son malos, uno sólo encontré que permitía guardar los posts pero no lo pude integrar al template que se está usando. 

Te armo el endpoint para dar soporte a eso Seba mientras tanto, y otro para que consultes los favoritos de X usuario.

**Comment by matiascaputti** [comment]
**GET api/favorites/{userId}** _(ejemplo api/favorites/127 tiene cargados 3 favoritos)_
**POST api/favorites** {userId, productId}
**DELETE api/favorites** {userId, ProductId}
