### ISSUE TITLE
Agregar identificación del error en responses. (endpoint de register)

### ISSUE THREAD

**Issue by sebastiancesar** [CeiboIT/sof-tokyo-node-server#61]
Cuando se produce un error durante el registro de un nuevo usuario, en lugar de devolver un string con la descripción del error, deberiamos devolver un identificador de ese error,
ejemplo:
001 - Password invalida,
002 - Usuario registrado
etc.
Por ahora, solo encontre "usuario registrado". En lineas generales, los backend deben devolver siempre ids , así el es client el que decide que texto mostrar, ya que el client es el que está de cara al usuario y puede saber el locale.

**Comment by Epotignano** [comment]
Entendido!

Potignano Emiliano - CeiboIT

web: www.ceiboit.com
Linkedin: https://ar.linkedin.com/pub/emiliano-potignano/76/242/192
Github: https://github.com/Epotignano
phone: +54 221 525 5778
address: 11 num 2175 b/510 & 511, La Plata, Buenos Aires, Argentina.

**Comment by matiascaputti** [comment]
Agregué para error de email ("000"), y error de username ("001"), los otros campos no deberían tirar error.
Si aparece otro error que quieran que agregue al register me avisan!
