### ISSUE TITLE
Apuntar DNS de Lolipop a Hostgator

### ISSUE THREAD

**Issue by Epotignano** [CeiboIT/sof-tokyo-node-server#7]
Danos una mano de oro!!! Seba! jaja

**Comment by matiascaputti** [comment]
@Epotignano esto estaría listo?

**Comment by Epotignano** [comment]
No! Ultimo paso!

Potignano Emiliano - CeiboIT

web: www.ceiboit.com
Linkedin: https://ar.linkedin.com/pub/emiliano-potignano/76/242/192
Github: https://github.com/Epotignano
phone: +54 221 525 5778
address: 11 num 2175 b/510 & 511, La Plata, Buenos Aires, Argentina.

2016-01-05 11:22 GMT-03:00 Matías Caputti notifications@github.com:
